### ISSUE TITLE
Doesn't work without the VimL code?

### ISSUE THREAD

**Issue by tssm** [jacobsimpson/nvim-example-lua-plugin#2]
Hey @jacobsimpson,

I have been playing with this and if I understand [this comment](https://github.com/jacobsimpson/nvim-example-lua-plugin/blob/master/plugin/nvim-example-lua-plugin.vim#L2) the `vim-example-lua-plugin.vim` could be deleted and then the print statement in `vim-example-lua-plugin.lua` should be executed but I don't see that behavior. Am I interpreting it wrong?

**Comment by tssm** [comment]
Sorry, I read too fast. The code can be removed, not the file 🙄

**Comment by tssm** [comment]
@jacobsimpson sorry again but what its the point of the `plugin/vim-example-lua-plugin.lua` file? It doesn't seem to be called at all

**Comment by jacobsimpson** [comment]
I think you are correct, and it is not getting executed at all. I'm investigating whether or not I am missing something, but it seems to me that it should be deleted.

**Comment by jacobsimpson** [comment]
I removed the file, and some other code that was complicating the example.
