### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to call global 'lua_function' (a nil va lue)

### ISSUE THREAD

**Issue by sogaiu** [jacobsimpson/nvim-example-lua-plugin#7]
I found that with `NVIM v0.5.0-424-g6ca7ebb34`, the `<M-C-G>` key sequence leads to:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call global 'lua_function' (a nil va lue)
```
Changing:
```
nmap <M-C-G> :lua lua_function()<CR>
```
to:
```
nmap <M-C-G> :lua myluadmodeul.lua_function()<CR>
```

in `nvim-example-lua-plugin.vim` seems to make things work better.

----

P.S. Thanks a lot for putting this repository together.  Much appreciated :+1:

**Comment by michael-angelozzi** [comment]
Experiencing the same.

**Comment by jacobsimpson** [comment]
I adjusted the pattern of how I exported the Lua function from the module and forgot to update the calling code. Should be working now.
